## 1. Import data

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Import data

df_understat = pd.read_csv("understat.com.csv")
df_understat

,Unnamed: 0,Unnamed: 1,position,team,matches,wins,draws,loses,scored,missed,...,xGA,xGA_diff,npxGA,npxGD,ppda_coef,oppda_coef,deep,deep_allowed,xpts,xpts_diff
0,La_liga,2014,1,Barcelona,38,30,4,4,110,21,...,28.444293,7.444293,24.727907,73.049305,5.683535,16.367593,489,114,94.0813,0.0813
1,La_liga,2014,2,Real Madrid,38,30,2,6,118,38,...,42.607198,4.607198,38.890805,47.213090,10.209085,12.929510,351,153,81.7489,-10.2511
2,La_liga,2014,3,Atletico Madrid,38,23,9,6,67,29,...,29.069107,0.069107,26.839271,25.748737,8.982028,9.237091,197,123,73.1353,-4.8647
3,La_liga,2014,4,Valencia,38,22,11,5,70,32,...,39.392572,7.392572,33.446477,16.257501,8.709827,7.870225,203,172,63.7068,-13.2932
4,La_liga,2014,5,Sevilla,38,23,7,8,71,45,...,47.862742,2.862742,41.916529,20.178070,8.276148,9.477805,305,168,67.3867,-8.6133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,RFPL,2019,12,PFC Sochi,30,8,9,13,40,39,...,38.850259,-0.149741,32.780898,-0.096048,12.838079,10.562327,175,206,38.6587,5.6587
680,RFPL,2019,13,FK Akhmat,30,7,10,13,27,46,...,40.626196,-5.373804,38.363370,-10.495864,11.199502,10.806357,124,206,36.5424,5.5424
681,RFPL,2019,14,Krylya Sovetov Samara,30,8,7,15,33,40,...,42.980693,2.980693,37.550114,-7.777201,11.949903,10.080858,103,215,36.3363,5.3363
682,RFPL,2019,15,FC Tambov,30,9,4,17,37,41,...,39.747938,-1.252062,34.468003,-12.231948,14.666049,9.192768,150,270,29.2413,-1.7587
683,RFPL,2019,16,FC Orenburg,30,7,6,17,28,52,...,37.169797,-14.830203,32.644130,0.201339,12.830908,9.464581,153,215,39.2364,12.2364

In [8]:
#Renaming wrongly named columns

col_names = df_understat.columns.to_list()

col_names[0] = "League"
col_names[1] = "Season_start"

df_understat.columns = col_names

In [9]:
print(f"There is {df_understat.shape[0]} rows and {df_understat.shape[1]} columns in this dataset.")

There is 684 rows and 24 columns in this dataset.

In [11]:
df_understat.info()

print(f"\nThere is zero null values")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 684 entries, 0 to 683
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   League        684 non-null    object
 1   Season_start  684 non-null    int64
 2   position      684 non-null    int64
 3   team          684 non-null    object
 4   matches       684 non-null    int64
 5   wins          684 non-null    int64
 6   draws         684 non-null    int64
 7   loses         684 non-null    int64
 8   scored        684 non-null    int64
 9   missed        684 non-null    int64
 10  pts           684 non-null    int64
 11  xG            684 non-null    float64
 12  xG_diff       684 non-null    float64
 13  npxG          684 non-null    float64
 14  xGA           684 non-null    float64
 15  xGA_diff      684 non-null    float64
 16  npxGA         684 non-null    float64
 17  npxGD         684 non-null    float64
 18  ppda_coef     684 non-null    float64
 19  oppda_coef    684 non-null    float64
 20  deep          684 non-null    int64
 21  deep_allowed  684 non-null    int64
 22  xpts          684 non-null    float64
 23  xpts_diff     684 non-null    float64
dtypes: float64(11), int64(11), object(2)
memory usage: 128.4+ KB

There is zero null values

## 2. Initial analysis

## 3. Leagues analysis

## 4. Analysis of more important statistic

## 5. Teams analysis